import * as FontColor from './fontColor';

const fontColorMap = [
    FontColor.fontArray0,
    FontColor.fontArray1,
    FontColor.fontArray2,
    FontColor.fontArray3,
    FontColor.fontArray4,
    FontColor.fontArray5,
    FontColor.fontArray6,
    FontColor.fontArray7,
    FontColor.fontArray8,
    FontColor.fontArray9,
    FontColor.fontArray10,
    FontColor.fontArray11,
    FontColor.fontArray12,
    FontColor.fontArray13,
    FontColor.fontArray14,
    FontColor.fontArray15,
    FontColor.fontArray16,
    FontColor.fontArray17,
    FontColor.fontArray18,
    FontColor.fontArray19,
    FontColor.fontArray20,
    FontColor.fontArray21,
    FontColor.fontArray22,
    FontColor.fontArray23,
    FontColor.fontArray24,
    FontColor.fontArray25,
    FontColor.fontArray27,
    FontColor.fontArray28,
    FontColor.fontArray30,
    FontColor.fontArray31,
    FontColor.fontArray32,
    FontColor.fontArray34,
    FontColor.fontArray35,
    FontColor.fontArray37,
];

export default fontColorMap;
